// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbQQdOiLJ3_RD6gT6047XzN7fQFmM7vw',
    appId: '1:456972501781:web:5311c7f3032ee857275f1c',
    messagingSenderId: '456972501781',
    projectId: 'flash-chat-updated-8bf76',
    authDomain: 'flash-chat-updated-8bf76.firebaseapp.com',
    storageBucket: 'flash-chat-updated-8bf76.appspot.com',
    measurementId: 'G-93XHFH58QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4mIlrNdK2FSXuaOElKA_gBRHixtub-M',
    appId: '1:456972501781:android:f8d78e4b27febfbc275f1c',
    messagingSenderId: '456972501781',
    projectId: 'flash-chat-updated-8bf76',
    storageBucket: 'flash-chat-updated-8bf76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbX_2mc1MfhDbdJz2wLz5E71Mvb8zG5hY',
    appId: '1:456972501781:ios:a2528cbe25ac8299275f1c',
    messagingSenderId: '456972501781',
    projectId: 'flash-chat-updated-8bf76',
    storageBucket: 'flash-chat-updated-8bf76.appspot.com',
    iosClientId: '456972501781-rou1t709rvc0dc4hn5qqi1pht96i6dks.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatUpdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbX_2mc1MfhDbdJz2wLz5E71Mvb8zG5hY',
    appId: '1:456972501781:ios:a2528cbe25ac8299275f1c',
    messagingSenderId: '456972501781',
    projectId: 'flash-chat-updated-8bf76',
    storageBucket: 'flash-chat-updated-8bf76.appspot.com',
    iosClientId: '456972501781-rou1t709rvc0dc4hn5qqi1pht96i6dks.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatUpdated',
  );
}
